# Generated by Django 5.0.6 on 2024-07-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
    ]
