# Generated by Django 5.0.3 on 2024-06-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='board_id',
        ),
        migrations.AddField(
            model_name='list',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
