# Generated by Django 5.0.3 on 2024-07-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_num_lists'),
        ('list', '0003_alter_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='board',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
